"""add_context_summary_to_chat_rooms

Revision ID: 31f88ca560c3
Revises: 11129e3565a6
Create Date: 2026-04-09 14:19:06.776392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f88ca560c3'
down_revision: Union[str, Sequence[str], None] = '11129e3565a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholder_chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_summary', sa.Text(), nullable=True, comment='历史消息压缩摘要'))
        batch_op.add_column(sa.Column('summary_up_to_message_id', sa.Integer(), nullable=True, comment='摘要覆盖到的最新消息ID'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholder_chat_rooms', schema=None) as batch_op:
        batch_op.drop_column('summary_up_to_message_id')
        batch_op.drop_column('context_summary')

    # ### end Alembic commands ###
