"""create stakeholder_personas table

Revision ID: ac7fa9a4e143
Revises: 31f88ca560c3
Create Date: 2026-04-13 16:25:47.232398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7fa9a4e143'
down_revision: Union[str, Sequence[str], None] = '31f88ca560c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stakeholder_personas',
    sa.Column('id', sa.String(length=50), nullable=False, comment='画像ID (与 markdown 文件名一致)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='角色名'),
    sa.Column('role', sa.String(length=255), nullable=False, comment='职位/角色'),
    sa.Column('avatar_color', sa.String(length=20), nullable=True, comment='头像颜色'),
    sa.Column('organization_id', sa.Integer(), nullable=True, comment='所属组织ID'),
    sa.Column('team_id', sa.Integer(), nullable=True, comment='所属团队ID'),
    sa.Column('profile_summary', sa.Text(), server_default='', nullable=False, comment='画像摘要'),
    sa.Column('full_content', sa.Text(), server_default='', nullable=False, comment='v1 markdown 全文'),
    sa.Column('voice_id', sa.String(length=100), nullable=True, comment='TTS voice id'),
    sa.Column('voice_speed', sa.Float(), server_default='1.0', nullable=False, comment='TTS 语速'),
    sa.Column('voice_style', sa.String(length=50), nullable=True, comment='TTS 风格'),
    sa.Column('structured_profile', sa.JSON(), nullable=True, comment='v2 5-layer 结构化数据 (hard_rules/identity/expression/decision/interpersonal)'),
    sa.Column('evidence_citations', sa.JSON(), nullable=True, comment='v2 证据链 (list[Evidence])'),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False, comment='schema 版本: 1=legacy markdown, 2=structured'),
    sa.Column('source_materials', sa.JSON(), nullable=True, comment='v2 原始素材 id/片段列表'),
    sa.Column('legacy_content', sa.Text(), nullable=True, comment='迁移前 markdown 原文备份'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.PrimaryKeyConstraint('id'),
    comment='利益相关者画像 (v1 legacy markdown + v2 5-layer 结构化)'
    )
    with op.batch_alter_table('stakeholder_personas', schema=None) as batch_op:
        batch_op.create_index('ix_stakeholder_personas_schema_version', ['schema_version'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stakeholder_personas', schema=None) as batch_op:
        batch_op.drop_index('ix_stakeholder_personas_schema_version')

    op.drop_table('stakeholder_personas')
    # ### end Alembic commands ###
